Sports_Management_System/Sports_Management_System/Events/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Events, name='Events'),
    path('<int:event_id>/',views.display_event,name='display_event'),
]

Sports_Management_System/Sports_Management_System/Feedback/urls.py
from django.urls import path
from . import views
app_name='Feedback'

urlpatterns = [
    path('', views.Feedback, name='Feedback'),
    path('save_feed/',views.Save,name="save_feed"),
]

Sports_Management_System/Sports_Management_System/Notifications/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('',views.notif,name='notif'),
]

Sports_Management_System/Sports_Management_System/Sports_Management_System/urls.py
from django.contrib import admin
from django.urls import path,include
# for login logout signup and all following view is imported from django lib.
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import url

admin.site.site_header =  "Sports Management System"
admin.site.index_title = "Welcome to Applications"
admin.site.site_title = "Sports Admin Portal"
urlpatterns = [
    path('',include('Home_Page.urls')),
    path('register/',include('Home_Page.urls')),
    path('admin/', admin.site.urls),
    path('Events/', include('Events.urls')),
    path('Feedback/', include('Feedback.urls')),
    path('Resource_Management/', include('Resource_Management.urls')),
    path('Notifications/',include('Notifications.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sports_Management_System/Sports_Management_System/Events/models.py
from django.db import models
from django.db.models import Model
# from phonenumber_field.modelfields import PhoneNumberField
# from phone_field import PhoneField

# Create your models here.
class event(models.Model):
    name = models.CharField(max_length=50)
    timestamp = models.DateTimeField(default='')
    timestamp_for_finish = models.DateTimeField(default='')
    organiser = models.CharField(max_length=100)
    about = models.TextField(default='')
    # rules = models.TextField(default='')
    # csvfile = models.FileField(upload_to='csvfile_for_guest/')
    contact = models.TextField(default='')
    link = models.URLField(default='',blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'events'

class rule(models.Model):
    event_id = models.IntegerField()
    event_name = models.CharField(max_length=50,default='')
    rule1 = models.TextField(default='')
    rule2 = models.TextField(default='',blank=True)
    rule3 = models.TextField(default='',blank=True)
    rule4 = models.TextField(default='',blank=True)
    rule5 = models.TextField(default='',blank=True)

    def __str__(self):
        return self.event_name


class guest(models.Model):
    id_for_event = models.IntegerField()
    name = models.CharField(max_length=100)
    motto = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')

class prize(models.Model):
    event_id = models.IntegerField()
    event_name = models.CharField(max_length=100)
    first_prize = models.CharField(max_length=100)
    second_prize = models.CharField(max_length=100,default='',blank=True)
    third_prize = models.CharField(max_length=100,default='',blank=True)

    def __str__(self):
        return self.event_name

class contact(models.Model):
    event_id = models.IntegerField()
    event_name = models.CharField(max_length=50)
    contact_name = models.CharField(max_length=50)
    contact_phone = models.CharField(max_length=12)
    contact_email = models.EmailField(max_length=50,blank=True)

    def __str__(self):
        return self.contact_name

Sports_Management_System/Sports_Management_System/Feedback/models.py
from django.db import models

# Create your models here.
class feedback(models.Model):
    Name = models.CharField(max_length=200)
    event = models.CharField(max_length=150)
    event_id = models.IntegerField()
    email = models.EmailField()
    details = models.TextField()
    happy = models.BooleanField()
    date = models.DateField(auto_now_add=True)


    def __str__(self):
        return self.Name

Sports_Management_System/Sports_Management_System/Notifications/models.py
from django.db import models

# Create your models here.

class notif_model(models.Model):
	heading = models.CharField(max_length=255)
	subject = models.TextField(default='')

	def __str__(self):
		return self.heading

Sports_Management_System/Sports_Management_System/Feedback/forms.py
from django import forms 
from .models import feedback
 
 
class FeedbackForm(forms.ModelForm):
    # name = forms.CharField(max_length=200)
    # event_name = forms.CharField(max_length=200)
    # event_id = forms.IntegerField(help_text="Enter Event ID here")
    # email = forms.EmailField(max_length=200)
    # details = forms.CharField()
    # happy=forms.BooleanField()

    class Meta:
        model = feedback
        exclude = []


    # class Meta:
    #     model = feedback
    #     exclude = ['happy','date']
        
    # customer_name = forms.CharField(max_length=100,
    #                         widget=forms.TextInput(attrs={
    #                         'class':'form-control',
    #                         'placeholder':'Your Name'
    #                         }))
    # event = forms.CharField(max_length=100,
    #                         widget=forms.TextInput(attrs={
    #                         'class':'form-control',
    #                         'placeholder':'Participating Sport'
    #                         }))
    # email = forms.EmailField(
    #                         widget=forms.TextInput(attrs={
    #                         'class':'form-control',
    #                         'placeholder':'Tournament Id'
    #                         }))
    # details = forms.CharField(
    #                         widget=forms.Textarea(attrs={
    #                         'class':'form-control',
    #                         'placeholder':'Your Phone Number'
    #                         }))
    # happy = forms.BooleanField(
    #                         widget=forms.TextInput(attrs={
    #                         'class':'form-control',
    #                         'placeholder':'Happy (Yes/No)'
    #                         }))




    # class Meta:
    #     model = feedback
    #     exclude = []

Sports_Management_System/Sports_Management_System/Events/views.py
from django.shortcuts import render
from .models import *
from Home_Page.models import *
import time
from django.utils import timezone
# Create your views here.

def Events(request):
    events = event.objects.all()
    upcoming = []
    past = []

    for i in events:
        details = {
            'event_id' : i.id,
            'event_name' : i.name,
            'organiser' : i.organiser,
            'time' : i.timestamp,
        }

        current = str(timezone.now())
        if(current<str(i.timestamp)):
            upcoming.append(details)
        elif(current>str(i.timestamp_for_finish)):
            past.append(details)


    context = {'uevents' : upcoming, 'pevents' : past}

    return render(request, 'Events.html', context)


# Code to ensure leaderboard sorting
# def sortSixth(val):
#     return val['point']


def display_event(request,event_id):
    # code to maintain events
    try:
        evnt = event.objects.get(pk=event_id)
    except event.DoesNotExist:
        raise Http404("Event does not exist")

    #code to manage guests
    guests = guest.objects.all()
    guest_for_this = []
    for i in guests:
        if i.id_for_event == event_id:
            guest_for_this.append(i)


    # code to maintain rules
    rules = rule.objects.all()
    rule_for_this = []
    for i in rules:
        if i.event_id == event_id:
            rule_for_this.append(i)

    exact_rules =[]
    temp = '';
    for i in rule_for_this:
        # for j in range(1,6):
            # temp = 'rule'+str(j)
            if i.rule1:
                exact_rules.append(i.rule1)
            if i.rule2:
                exact_rules.append(i.rule2)
            if i.rule3:
                exact_rules.append(i.rule3)
            if i.rule4:
                exact_rules.append(i.rule4)
            if i.rule5:
                exact_rules.append(i.rule5)

    #code to maintain Prizes
    prizes = prize.objects.all()
    prize_for_this = []
    for p in prizes:
        if p.event_id == event_id:
             prize_for_this.append(p)
    

    #code to maintain contact
    contacts = contact.objects.all()
    contact_for_this = []
    for i in contacts:
        if i.event_id == event_id:
            contact_for_this.append(i)

    #code to maintain leaderboard
    candi = RegistrationData.objects.all().order_by('-point')  
    cand_for_this = []
    for i in candi:
        if i.tournamentid == event_id:
            cand_for_this.append(i)

    # cand_for_this.sort(key=sortSixth)

    pass_to_display = {'event_details' : evnt, 'guest_details' : guest_for_this,
    'rules': exact_rules,'winners':prize_for_this,
    'contact_details':contact_for_this,"candidate":cand_for_this}


    return render(request,'display.html',pass_to_display)

Sports_Management_System/Sports_Management_System/Feedback/views.py
from django.shortcuts import render,redirect
from .forms import FeedbackForm
from .models import feedback

# Create your views here.
def Feedback(request):
    print("Hello Feedback called")
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,'thanks.html')
    else:
        form = FeedbackForm()
    return render(request, 'feedback.html', {'form':form})

    # if request.method == 'POST':
    #     form = FeedbackForm(request.POST)

    # if form.is_valid():
    #     my_feedback = feedback(customer_name = form.cleaned_data['Your_Name'],
    #         event = form.cleaned_data['Event'],
    #         email = form.cleaned_data['Email'],
    #         details = form.cleaned_data['Details'],
    #         # happy = form.cleaned_data['Happy'],
    #         )
    #     my_feedback.save()

    # return render(request,'thanks.html')

    
    # if request.method == 'POST':
    #     form = FeedbackForm(request.POST)

    #     if form.is_valid():
    #         form.save()
    #         return render(request, 'thanks.html')
    # else:
    #     form = FeedbackForm()
    # return render(request, 'feedback.html', {'form':form})

def Save(request):

    form = FeedbackForm(request.POST)

    if form.is_valid():
        my_feedback = feedback(customer_name = form.cleaned_data['customer_name'],
            event = form.cleaned_data['event'],
            email = form.cleaned_data['email'],
            details = form.cleaned_data['details'],
            happy = form.cleaned_data['happy'],
            )
        my_feedback.save()
        
    return render(request,'thanks.html')

Sports_Management_System/Sports_Management_System/Notifications/views.py
from django.shortcuts import render
from .models import *

# Create your views here.

def notif(request):
	updates = notif_model.objects.all()

	crnt_notif = []

	for i in updates:
		crnt_notif.append(i)

	pass_to_notif = {
		'crnt_notif':crnt_notif,
	}

	return render(request,'notifications.html',pass_to_notif)

Sports_Management_System/Sports_Management_System/templates/Events.html
<!-- events = {
	'event_name' : event.name,
	'organiser' : event.organiser,
	'time' : event.timestamp,
} -->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Events</title>
    
    <!-- Stylesheets -->
    <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">


    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/d5f63bfac1.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/7959a9fa31.js" crossorigin="anonymous"></script>

</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
          <div style="width: 10%;">
           <a href="/"> <img src="/static/images/logo.png" alt="Logo" style="width: 110px">
           </a>
          </div>
            <div class="container">
        <div class="column is-offset-0 is-6">
          <h2 class="title" style="font-size: 4rem;color: red; text-align: left;font-style: normal;">
            Welcome To The Events
          </h2 >
        </div>
            </div>
        </div>
  </section>


	<section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-1 is-4">
					<section class="hero is-primary" >
						<div class="hero-body" >
							<div class="container">
								<h1 style="font-size: 2rem; text-align: left; color: white;">
									Upcoming Event/s
								</h1>
							</div>
						</div>
					</section>
                    {% for event in uevents %}
                    <div class="box">
                        <article class="media">
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                      <a href="/Events/{{event.event_id}}/"><u style="color: #01c5c4;"><span class="title" style="color: #01c5c4;">
                                        {{  event.event_name  }}(Id: {{event.event_id}})</span></u></a>
                                        <br>
                                        
                                        <span class="subtitle">{{ event.organiser }}</span>
                                        <br>
                                        
                                        <span class="subtitle">{{ event.time }}</span>
                                    </p>
                                </div>
                            </div>
                        </article>
                    </div>
                    {% endfor %}
				</div>
				<div class="column is-offset-3 is-4">
					<section class="hero is-primary" >
						<div class="hero-body">
							<div class="container">
								<h1 style="font-size: 2rem;text-align: left; color: white;">
									Past Event/s
								</h1>
							</div>
						</div>
					</section>
                    {% for event in pevents %}
                    <div class="box">
                        <article class="media">
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                      <a href="/Events/{{event.event_id}}/"><u style="color: #01c5c4;"><span class="title" style="color: #01c5c4;">
                                        {{  event.event_name  }} (Id: {{event.event_id}})</span></u></a>
                                        <!-- Try to hover above link -->
                                        <br>
                                        
                                        <span class="subtitle">{{ event.organiser }}</span>
                                        <br>
                                        
                                        <span class="subtitle">{{ event.time }}</span>
                                    </p>
                                </div>
                            </div>
                        </article>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
</body>

<hr>

<!-- Footer -->
<footer class="page-footer font-small mdb-color pt-4" style="background-color: #cfd3ce;">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Footer links -->
    <div class="row text-center text-md-left mt-3 pb-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
        <h2 class="text-uppercase mb-4 font-weight-bold">About</h2>
        <p style="font-size: 1.3rem;">This Sports Management System Helps Admin to Regulate Events and Users to Enjoy events.Come on and all Do join this Sports Season and Take care of Your Health and stay Safe and Secure.<i class="fa fa-heart" style="font-size:24px;color:red"></i></p>
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
        <h2 class="text-uppercase mb-4 font-weight-bold">Features</h2>
        <p style="font-size: 1.3rem; padding-bottom: 10px;">User Friendly</p>
         <p style="font-size: 1.3rem; padding-bottom: 10px;">Sends Email Notifications</p>
         <p style="font-size: 1.3rem; padding-bottom: 10px;">Current,Upcoming and Past Events</p>
         <p style="font-size: 1.3rem; padding-bottom: 10px;">Leaderboard</p>
        
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
        <h3 class="text-uppercase mb-4 font-weight-bold">Links</h3>
        <p style="padding-top: 0px;">
          <p><a href="/Notifications/" style="font-size: 1.4rem;">Notifications</a></p>
         <p><a href="/Feedback/" style="font-size: 1.4rem;">Give Feedback</a></p>
         <p><a href="/Events/" style="font-size: 1.4rem;">Event Details</a></p>
         <p><a href="/register/" style="font-size: 1.4rem;">Register For an Event</a>
         </p>
          </p>
      </div>

      <!-- Grid column -->
      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
        <h2 class="text-uppercase mb-4 font-weight-bold">Contact</h2>
        <p>
          <p style="font-size: 1.4rem;"><i class="fas fa-home mr-3" style="font-size: 1.5rem"></i> 
           IIIT Lucknow </p>
        </p>
        <p style="padding-top: 10px;">
          <h4>Sachin Pal</h4>
          <p style="font-size: 1.4rem;">
            <a href="mailto:Admin@gmail.com" style="color: #4a4a4a">
            <i class="fas fa-envelope mr-3" style="font-size: 1.5rem"></i>lit2018016@iiitl.ac.in</a>
          </p>
        </p>
        <p style="padding-top: 10px;">
        <p>
          <h4>Samyak Jain</h4>
          <p style="font-size: 1.4rem;">
            <a href="mailto:Admin@gmail.com" style="color: #4a4a4a">  
            <i class="fas fa-envelope mr-3" style="font-size: 1.5rem"></i>lit2018056@iiitl.ac.in</a>
          </p>
        </p>
        <p style="font-size: 1.4rem; padding-top: 5px;">
          <i class="fas fa-phone mr-3" style="font-size: 1.5rem;"></i> + 01 234 567 88</p>
        <!-- <p>
          <i class="fas fa-print mr-3"></i> + 01 234 567 89</p> -->
      </div>

    </div>


    <hr>

    <div class="row " style="text-align: center;">
      <div class="col-md- col-lg-4 ml-lg-0" style="max-width: 100%; flex: none;">

        <!-- Social buttons -->
        <!-- <div class="text-center text-md-right">
          <ul class="list-unstyled list-inline">
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-google-plus-g"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div> -->
   <a href="https://twitter.com/login" style="color: #4a4a4a">
  <i class="fab fa-twitter foo"></i></a>
  <a href="https://www.facebook.com/" style="color: #4a4a4a">
  <i class="fab fa-facebook-f foo"></i></a>
  <a href="https://www.instagram.com/" style="color: #4a4a4a">
  <i class="fab fa-instagram foo"></i>
  </a>
  <a href="mailto:Admin@gmail.com" style="color: #4a4a4a"><i class="fas fa-envelope foo"></i> </a>
  <p class="copy-right c">© Copyright 2020 Sports</p>
      </div>
     
    </div>

  </div>
  <br>
  <br>
  
</footer>

</html>

Sports_Management_System/Sports_Management_System/templates/feedback.html
{% extends 'base.html' %}

{% block title %}Feedback Form{% endblock %}

{% block body %}



<section class="hero is-primary">
        <div class="hero-body">
          <div style="width: 10%;">
           <a href="/"> <img src="/static/images/logo.png" alt="Logo" style="width: 110px">
           </a>
          </div>
            <div class="container">
        <div class="column is-offset-0 is-6">
          <h2 class="title" style="font-size: 4rem;color: red;">
            Feedback Forum
          </h2 >
        </div>
            </div>
        </div>
  </section>



<div class="container">
  <!-- <h2 style="font-size: 5rem;color: red;">Welcome to Tournament Registration</h2> -->

  <!-- <form action="{% url 'Feedback:save_feed' %}" method="post"> -->
  <form method = "post" class="feedback">
    {% csrf_token %} 
    {% for field in form %}
    <div class="row">
       <div class="col-md-2">    
        {{ field.label_tag }}
        {% if field.help_text %}
          <sup>{{ field.help_text }}</sup>
        {% endif %}
        {{ field.errors }}
       </div><div class="col-md-20 pull-left">
         {{ field }}
       </div>
    </div>
   {% endfor %}

    <input type="submit" value="Submit" class="btn btn-success">
  </form>
  <!-- <div class="form-group">
    <label>Your_Name</label>
    {{form.name}}
  </div>
  <div class="form-group">
    <label >Event</label>
    {{form.event_name}}
  </div>
  <div class="form-group">
    <label >Email</label>
    {{form.email}}
  </div>
  <div class="form-group">
    <label >Details</label>
    {{form.details}}
  </div>
  <div class="form-group">
    <label >Happy</label>
    {{form.happy}}
  </div> -->
  <!-- <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Happy</label>
    {{form.happy}}
  </div> -->
    
</form>
    <!-- {{form.as_p}} -->
</div>


<hr>


{% endblock %}

Sports_Management_System/Sports_Management_System/templates/notifications.html
{% extends 'base.html'%}

{% block title %}Notifications {% endblock %}


{% block body %}

	<section class="hero is-primary">
        <div class="hero-body">
          <div style="width: 10%;">
           <a href="/"> <img src="/static/images/logo.png" alt="Logo" style="width: 110px">
           </a>
          </div>
            <div class="container">
        <div class="column is-offset-0 is-6">
          <h2 class="title" style="font-size: 4rem;color: red;">
            LATEST UPDATES
          </h2 >
        </div>
            </div>
        </div>
  </section>
	
	<br>
	<div class="col-md-9" style="margin-left: 200px;">
              <div class="panel panel-default">
                  <div class="panel-heading" style="background-color: #8CD6EF;">
                    <!-- <span class="glyphicon glyphicon-bullhorn"></span> -->
                    <h2><b><i class="fas fa-bullhorn"></i>  RECENT ANNOUNCEMENTS</b> </h2>
                    
                  </div>
               </div>
                 <div class="panel-body">
                 	{% for i in crnt_notif %}
                    <div class="row" style="display: table-row;">
                      <div class="col-xs-12">
                          <ul>
						  <li class="news-item" style="color:red; border-bottom: 2px dotted grey;padding-top: 30px; padding-left: 30px;
              text-align: left;">
                                <b>
                                    <a href="#" style="color:red;">{{i.heading}}</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="#" style="color:red">{{i.subject}}</a>
                                    <!-- <IMG height=20 src="../images/new.gif" width=25 border=0 /> -->
                                </b>
                            </li>
                        </ul>
                     </div>
                    </div>
                    {% endfor %}
            	</div>
        </div>

<br>
{% endblock %}

Sports_Management_System/Sports_Management_System/templates/register.html
{% extends 'base.html' %}

{% block title %} Candidate Registration {% endblock %}

{% block body %}

<section class="hero is-primary">
        <div class="hero-body">
          <div style="width: 10%;">
           <a href="/"> <img src="/static/images/logo.png" alt="Logo" style="width: 110px">
           </a>
          </div>
            <div class="container">
        <div class="column is-offset-0 is-12">
          <h2 class="title" style="font-size: 4rem;color: red;">
            Welcome To Tournaments Registrations
          </h2>
        </div>
            </div>
        </div>
  </section>


<div class="container">
  <!-- <h2 style="font-size: 5rem;color: red;">Welcome to Tournament Registration</h2> -->

  <form action="{% url 'addUser' %}" method="post">
    {% csrf_token %} 
  <div class="form-group">
    <label >Player Name</label>
    {{form.username}}
  </div>
  <div class="form-group">
    <label >Sport Name</label>
    {{form.sportname}}
  </div>
  <div class="form-group">
    <label >Tournament Id</label>
    {{form.tournamentid}}
  </div>
  <div class="form-group">
    <label >Phone Number</label>
    {{form.phone}}
  </div>
  <div class="form-group">
    <label >Email address</label>
    {{form.email}}
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">All Done</label>
  </div>
    <input type="submit" name="" value="Register" class="btn btn-success">
</form>
    <!-- {{form.as_p}} -->
</div>

<hr>

{% endblock %}

Sports_Management_System/Sports_Management_System/templates/resource.html
{% extends 'base.html' %}

{% block title %} Available Resources {% endblock %}


{% block body %}
<section class="hero is-primary">
        <div class="hero-body">
        	<div style="width: 10%;">
           <a href="/"> <img src="/static/images/logo.png" alt="Logo" style="width: 110px">
           </a>
          </div>
            <div class="container">
        <div class="column is-offset-0 is-6">
          <h2 class="title" style="font-size: 4rem;color: red;">
            Resources Available
          </h2 >
        </div>
            </div>
        </div>
 </section>

<style>
table, th, td {
  border: 2px solid black;
  border-collapse: collapse;
  padding: 15px;
}
th, td {
  padding: 15px;
}
</style>

<table style="width: 100%; margin:20px;">
	<th>
		
		<h2><b>Item</b></h2>
	</th>
	<th>
		<h2><b>Available</b></h2>
	</th>
	<th>
		<h2><b>Requirement</b></h2>
	</th>
	<th>
		<h2><b>No of Items Needs to be purcahsed</b></h2>
	</th>
{% for i in resource %}
	<tr>
		<td>
		<h2>{{i.name}}</h2>
		</td>
		<td>{{i.available}}</td>
		<td>{{i.requirement}}</td>
		<td>
			{{i.purchase}}
		</td>	
	</tr>
{% endfor %}
</table>

<hr>
{% endblock %}

Sports_Management_System/Sports_Management_System/templates/thanks.html
<h1>Thanks for your response.</h1>
<a href="/">
<button type="button" onclick="alert('Thanks for the Participation')" style="font-size: 2rem; margin-left: 650px;margin-top: 50px;">Back To Home
</button>
</a>